package com.ssm.mapper;

import com.ssm.model.SalesRecord;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SalesRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesRecord
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesRecord
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    int insert(SalesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesRecord
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    int insertSelective(SalesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesRecord
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    SalesRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesRecord
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    int updateByPrimaryKeySelective(SalesRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesRecord
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    int updateByPrimaryKey(SalesRecord record);
}