package com.ssm.model;

import java.time.LocalDate;
// import java.util.Date;

public class SalesRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesRecord.id
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesRecord.bond_name
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    private String bondName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesRecord.sales_name
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    private String salesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesRecord.amount
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesRecord.created_time
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    private LocalDate createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesRecord.id
     *
     * @return the value of salesRecord.id
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesRecord.id
     *
     * @param id the value for salesRecord.id
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesRecord.bond_name
     *
     * @return the value of salesRecord.bond_name
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public String getBondName() {
        return bondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesRecord.bond_name
     *
     * @param bondName the value for salesRecord.bond_name
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public void setBondName(String bondName) {
        this.bondName = bondName == null ? null : bondName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesRecord.sales_name
     *
     * @return the value of salesRecord.sales_name
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public String getSalesName() {
        return salesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesRecord.sales_name
     *
     * @param salesName the value for salesRecord.sales_name
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public void setSalesName(String salesName) {
        this.salesName = salesName == null ? null : salesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesRecord.amount
     *
     * @return the value of salesRecord.amount
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesRecord.amount
     *
     * @param amount the value for salesRecord.amount
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesRecord.created_time
     *
     * @return the value of salesRecord.created_time
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public LocalDate getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesRecord.created_time
     *
     * @param createdTime the value for salesRecord.created_time
     *
     * @mbg.generated Mon Aug 23 10:03:55 CST 2021
     */
    public void setCreatedTime(LocalDate createdTime) {
        this.createdTime = createdTime;
    }
}